require: rubocop-rspec
AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 40
Metrics/LineLength:
  Max: 99
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
Metrics/MethodLength:
  Max: 30
Metrics/BlockNesting:
  Max: 4
Documentation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
